/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'tertiary-container': '#4f2e00',
        'secondary-fixed-dim': '#f8bc4b',
        'tertiary-fixed': '#ffddba',
        'on-surface': '#0d1c2e',
        'secondary-fixed': '#ffdeaa',
        'primary-fixed-dim': '#adc7f7',
        surface: '#f8f9ff',
        primary: '#002045',
        'inverse-primary': '#adc7f7',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed': '#d6e3ff',
        'on-secondary-fixed-variant': '#5f4100',
        'primary-container': '#1a365d',
        'surface-container-lowest': '#ffffff',
        'on-background': '#0d1c2e',
        'on-primary-container': '#86a0cd',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#f2bc82',
        outline: '#74777f',
        'on-surface-variant': '#43474e',
        'on-error': '#ffffff',
        'surface-dim': '#ccdbf4',
        'on-secondary-container': '#725000',
        'inverse-surface': '#223144',
        'error-container': '#ffdad6',
        'surface-tint': '#455f88',
        'on-primary-fixed-variant': '#2d476f',
        'outline-variant': '#c4c6cf',
        secondary: '#7d5700',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001b3c',
        'on-tertiary-fixed': '#2b1700',
        error: '#ba1a1a',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#c6955e',
        'on-secondary-fixed': '#271900',
        background: '#f8f9ff',
        tertiary: '#321b00',
        'secondary-container': '#ffc250',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed-variant': '#633f0f',
        'surface-container-highest': '#d4e4fc',
        'surface-variant': '#d4e4fc',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
