export interface InfraccionItem {
  id: number;
  registro: string | null;
  fecha_registro: string | null;
  fecha_emision: string | null;
  fecha_aprobacion: string | null;
  fecha_vencimiento: string | null;
  estado: string | null;
  codigo_infraccion: string | null;
  codigo_infraccion_ant: string | null;
  contravencion: string | null;
  articulo: string | null;
  literal: string | null;
  descripcion_articulo: string | null;
  periodo_fiscal: string | null;
  oficina: string | null;
  origen_registro: string | null;
  tipo_registro_infraccion: string | null;
  tipo_emision: string | null;
  tipo_deudor: string | null;
  codigo_usuario_registra: string | null;
  observacion: string | null;
  provincia: string | null;
  localidad: string | null;
  lugar_infraccion: string | null;
  canal: string | null;
  placa: string | null;
  tipo_identificacion_infractor: string | null;
  numero_identificacion_infractor: string | null;
  nombre_infractor: string | null;
  tipo_identificacion_propietario: string | null;
  numero_identificacion_propietario: string | null;
  nombre_propietario: string | null;
  indicador_bloqueada: string | null;
  indicador_acta_juzgamiento: string | null;
  indicador_modificada: string | null;
  indicador_calcula_recargo: string | null;
  valor_capital: number | null;
  valor_capital_exonerado: number | null;
  valor_recargo: number | null;
  valor_recargo_exonerado: number | null;
  valor_intereses: number | null;
  valor_total: number | null;
  hora_generacion: string | null;
  fecha_generacion: string | null;
  tipo_infraccion: string | null;
  codigo_usuario_aprueba: string | null;
  codigo_usuario_notifica: string | null;
  tipo_licencia: string | null;
  zona: string | null;
  distrito: string | null;
  circuito: string | null;
  dispositivo: string | null;
  geo_referencia_x: string | null;
  geo_referencia_y: string | null;
  tipo_identificacion_agente: string | null;
  numero_identificacion_agente: string | null;
  nombre_agente: string | null;
  codigo_agente_transito: string | null;
  tipo_infraccion_2: string | null;
  codigo_infraccion_origen: string | null;
  codigo_empresa_convenio: string | null;
  porcentaje_principal: string | null;
  porcentaje_convenio: string | null;
  cuenta_bancaria_principal: string | null;
  cuenta_bancaria_convenio: string | null;
  fecha_notificacion: string | null;
  fecha_pago: string | null;
  fecha_impugnacion: string | null;
  fecha_convenio: string | null;
  fecha_anulacion: string | null;
  fecha_coactiva: string | null;
  canal_catalogo_item_id: number | null;
  estado_catalogo_item_id: number | null;
  localidad_catalogo_item_id: number | null;
  origen_registro_catalogo_item_id: number | null;
  provincia_catalogo_item_id: number | null;
  tipo_deudor_catalogo_item_id: number | null;
  tipo_emision_catalogo_item_id: number | null;
  tipo_identificacion_agente_catalogo_item_id: number | null;
  tipo_identificacion_infractor_catalogo_item_id: number | null;
  tipo_identificacion_propietario_catalogo_item_id: number | null;
  tipo_licencia_catalogo_item_id: number | null;
  tipo_registro_infraccion_catalogo_item_id: number | null;
  zona_catalogo_item_id: number | null;
}

export interface InfraccionListResponse {
  items: InfraccionItem[];
  total: number;
  page: number;
  page_size: number;
}

export interface InfraccionFilters {
  fecha_desde: string;
  fecha_hasta: string;
  estado: string | null;
  contravencion: string | null;
}
