from sqlalchemy import BigInteger, Column, Date, DateTime, Integer, MetaData, Numeric, Table, Text, Time

axis_metadata = MetaData(schema="axis")

axis_impugnaciones = Table(
    "axis_impugnaciones",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("fecha_registro", DateTime),
    Column("fecha_acta", DateTime),
    Column("estado", Text),
    Column("codigo_infraccion_axis", Text),
    Column("contravencion", Text),
    Column("tipo_acta", Text),
    Column("articulo_original", Text),
    Column("monto_capital_original", Numeric(14, 2)),
    Column("observacion", Text),
    Column("deleted_at", DateTime(timezone=True)),
    Column("hora_generacion", Time),
    Column("fecha_generacion", Date),
    Column("numero_credito", Text),
    Column("numero_tramite", Text),
    Column("codigo_infraccion_generada_axis", Text),
    Column("juzgado", Text),
    Column("codigo_provincia", Text),
    Column("codigo_localidad", Text),
    Column("numero_proceso", Text),
    Column("monto_modificado_sentencia", Numeric(14, 2)),
    Column("puntos_original", Text),
    Column("puntos_modificados_sentencia", Text),
    Column("literal_original", Text),
    Column("articulo_modificado_sentencia", Text),
    Column("literal_modificado_sentencia", Text),
    Column("fecha_vencimiento_original", DateTime),
    Column("fecha_vencimiento_modificado_sentencia", DateTime),
    Column("sancion_original", Text),
    Column("sancion_modificada_sentencia", Text),
    Column("codigo_usuario", Text),
    Column("codigo_usuario_aprueba", Text),
    Column("numero_acta_juzgamiento", Text),
    Column("fecha_aprobacion", DateTime),
    Column("fecha_anulacion", DateTime),
    Column("codigo_usuario_anula", Text),
    Column("observacion_anulacion", Text),
    Column("articulo_original_catalogo_item_id", Integer),
    Column("articulo_modificado_sentencia_catalogo_item_id", Integer),
    Column("codigo_localidad_catalogo_item_id", Integer),
    Column("codigo_provincia_catalogo_item_id", Integer),
    Column("tipo_acta_catalogo_item_id", Integer),
)

axis_infracciones = Table(
    "axis_infracciones",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("fecha_registro", DateTime),
    Column("fecha_emision", DateTime),
    Column("fecha_aprobacion", DateTime),
    Column("fecha_vencimiento", DateTime),
    Column("estado", Text),
    Column("codigo_infraccion", Text),
    Column("codigo_infraccion_ant", Text),
    Column("contravencion", Text),
    Column("articulo", Text),
    Column("literal", Text),
    Column("descripcion_articulo", Text),
    Column("periodo_fiscal", Text),
    Column("oficina", Text),
    Column("origen_registro", Text),
    Column("tipo_registro_infraccion", Text),
    Column("tipo_emision", Text),
    Column("tipo_deudor", Text),
    Column("codigo_usuario_registra", Text),
    Column("observacion", Text),
    Column("provincia", Text),
    Column("localidad", Text),
    Column("lugar_infraccion", Text),
    Column("canal", Text),
    Column("placa", Text),
    Column("tipo_identificacion_infractor", Text),
    Column("numero_identificacion_infractor", Text),
    Column("nombre_infractor", Text),
    Column("tipo_identificacion_propietario", Text),
    Column("numero_identificacion_propietario", Text),
    Column("nombre_propietario", Text),
    Column("indicador_bloqueada", Text),
    Column("indicador_acta_juzgamiento", Text),
    Column("indicador_modificada", Text),
    Column("indicador_calcula_recargo", Text),
    Column("valor_capital", Numeric(14, 2)),
    Column("valor_capital_exonerado", Numeric(14, 2)),
    Column("valor_recargo", Numeric(14, 2)),
    Column("valor_recargo_exonerado", Numeric(14, 2)),
    Column("valor_intereses", Numeric(14, 2)),
    Column("valor_total", Numeric(14, 2)),
    Column("deleted_at", DateTime(timezone=True)),
    Column("hora_generacion", Time),
    Column("fecha_generacion", Date),
    Column("tipo_infraccion", Text),
    Column("codigo_usuario_aprueba", Text),
    Column("codigo_usuario_notifica", Text),
    Column("tipo_licencia", Text),
    Column("zona", Text),
    Column("distrito", Text),
    Column("circuito", Text),
    Column("dispositivo", Text),
    Column("geo_referencia_x", Text),
    Column("geo_referencia_y", Text),
    Column("tipo_identificacion_agente", Text),
    Column("numero_identificacion_agente", Text),
    Column("nombre_agente", Text),
    Column("codigo_agente_transito", Text),
    Column("tipo_infraccion_2", Text),
    Column("codigo_infraccion_origen", Text),
    Column("codigo_empresa_convenio", Text),
    Column("porcentaje_principal", Text),
    Column("porcentaje_convenio", Text),
    Column("cuenta_bancaria_principal", Text),
    Column("cuenta_bancaria_convenio", Text),
    Column("fecha_notificacion", DateTime),
    Column("fecha_pago", DateTime),
    Column("fecha_impugnacion", DateTime),
    Column("fecha_convenio", DateTime),
    Column("fecha_anulacion", DateTime),
    Column("fecha_coactiva", DateTime),
    Column("canal_catalogo_item_id", Integer),
    Column("estado_catalogo_item_id", Integer),
    Column("localidad_catalogo_item_id", Integer),
    Column("origen_registro_catalogo_item_id", Integer),
    Column("provincia_catalogo_item_id", Integer),
    Column("tipo_deudor_catalogo_item_id", Integer),
    Column("tipo_emision_catalogo_item_id", Integer),
    Column("tipo_identificacion_agente_catalogo_item_id", Integer),
    Column("tipo_identificacion_infractor_catalogo_item_id", Integer),
    Column("tipo_identificacion_propietario_catalogo_item_id", Integer),
    Column("tipo_licencia_catalogo_item_id", Integer),
    Column("tipo_registro_infraccion_catalogo_item_id", Integer),
    Column("zona_catalogo_item_id", Integer),
)

axis_juicios = Table(
    "axis_juicios",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("hora_generacion", Time),
    Column("codigo", Text),
    Column("tipo_identificacion", Text),
    Column("identificacion", Text),
    Column("nombre_completo", Text),
    Column("gestor_responsable", Text),
    Column("gestor_secretario", Text),
    Column("gestor_anulacion", Text),
    Column("gestor_suspension", Text),
    Column("gestor_reactivacion", Text),
    Column("motivo_anulacion", Text),
    Column("deleted_at", DateTime(timezone=True)),
    Column("fecha_generacion", Date),
    Column("fecha_registro", Date),
    Column("fecha_inicio_juicio", Date),
    Column("fecha_notificacion", Date),
    Column("fecha_pago", Date),
    Column("fecha_fin", Date),
    Column("fecha_anulacion", Date),
    Column("fecha_suspension", Date),
    Column("fecha_reactivacion", Date),
    Column("valor_capital", Numeric(14, 2)),
    Column("valor_interes", Numeric(14, 2)),
    Column("valor_multas", Numeric(14, 2)),
    Column("valor_costas", Numeric(14, 2)),
    Column("valor_total", Numeric(14, 2)),
    Column("tipo_identificacion_catalogo_item_id", Integer),
)

axis_crv = Table(
    "axis_crv",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("deleted_at", DateTime(timezone=True)),
)

axis_modificacion_infracciones = Table(
    "axis_modificacion_infracciones",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("deleted_at", DateTime(timezone=True)),
)

axis_pagos = Table(
    "axis_pagos",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("hora_generacion", Time),
    Column("tipo_recaudador", Text),
    Column("recaudador", Text),
    Column("comprobante_pago_interno", Text),
    Column("comprobante_pago_recaudador", Text),
    Column("tipo_servicio", Text),
    Column("tipo_documento", Text),
    Column("numero_documento", Text),
    Column("deleted_at", DateTime(timezone=True)),
    Column("fecha_generacion", Date),
    Column("fecha_operacion", DateTime),
    Column("fecha_transaccion", DateTime),
    Column("monto_recaudado", Numeric(14, 2)),
    Column("monto_cuenta_1", Numeric(14, 2)),
    Column("monto_cuenta_2", Numeric(14, 2)),
    Column("tipo_documento_catalogo_item_id", Integer),
    Column("tipo_recaudador_catalogo_item_id", Integer),
    Column("tipo_servicio_catalogo_item_id", Integer),
)

axis_titulos = Table(
    "axis_titulos",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("deleted_at", DateTime(timezone=True)),
)
