from sqlalchemy import BigInteger, Column, DateTime, MetaData, Numeric, Table, Text

axis_metadata = MetaData(schema="axis")

axis_impugnaciones = Table(
    "axis_impugnaciones",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("fecha_registro", DateTime),
    Column("fecha_acta", DateTime),
    Column("estado", Text),
    Column("codigo_infraccion_axis", Text),
    Column("contravencion", Text),
    Column("tipo_acta", Text),
    Column("articulo_original", Text),
    Column("monto_capital_original", Numeric(14, 2)),
    Column("observacion", Text),
)

axis_infracciones = Table(
    "axis_infracciones",
    axis_metadata,
    Column("id", BigInteger, primary_key=True),
    Column("registro", Text),
    Column("fecha_registro", DateTime),
    Column("fecha_emision", DateTime),
    Column("fecha_aprobacion", DateTime),
    Column("fecha_vencimiento", DateTime),
    Column("estado", Text),
    Column("codigo_infraccion", Text),
    Column("codigo_infraccion_ant", Text),
    Column("contravencion", Text),
    Column("articulo", Text),
    Column("literal", Text),
    Column("descripcion_articulo", Text),
    Column("periodo_fiscal", Text),
    Column("oficina", Text),
    Column("origen_registro", Text),
    Column("tipo_registro_infraccion", Text),
    Column("tipo_emision", Text),
    Column("tipo_deudor", Text),
    Column("codigo_usuario_registra", Text),
    Column("observacion", Text),
    Column("provincia", Text),
    Column("localidad", Text),
    Column("lugar_infraccion", Text),
    Column("canal", Text),
    Column("placa", Text),
    Column("tipo_identificacion_infractor", Text),
    Column("numero_identificacion_infractor", Text),
    Column("nombre_infractor", Text),
    Column("tipo_identificacion_propietario", Text),
    Column("numero_identificacion_propietario", Text),
    Column("nombre_propietario", Text),
    Column("indicador_bloqueada", Text),
    Column("indicador_acta_juzgamiento", Text),
    Column("indicador_modificada", Text),
    Column("indicador_calcula_recargo", Text),
    Column("valor_capital", Numeric(14, 2)),
    Column("valor_capital_exonerado", Numeric(14, 2)),
    Column("valor_recargo", Numeric(14, 2)),
    Column("valor_recargo_exonerado", Numeric(14, 2)),
    Column("valor_intereses", Numeric(14, 2)),
    Column("valor_total", Numeric(14, 2)),
)
